name: Go checks
concurrency:
  group: go-checks-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  go_checks:
    name: Go checks
    uses: ./.github/workflows/reusable_go_checks.yml
    with:
      sonarcloud_run: true
      sonarcloud_project_key: "elastiflow_pipelines"
    secrets:
      sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
