name: Go checks
concurrency:
  group: go-checks-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go_checks:
    name: Go checks
    uses: ./.github/workflows/reusable_go_checks.yml
    with:
      configure_git_goprivate: false
      unit_test_cmd: make test-unit
      unit_test_report_coverage_cmd: make test-unit-enforce-coverage
      go_version_file: "go.mod"
    secrets:
      go_dependency_fetcher_token: ${{ secrets.GO_DEPENDENCY_FETCH_TOKEN }}
