name: Release tag
concurrency:
  group: release-tag-${{ github.ref }}
on:
  push:
    branches:
      - main

jobs:
  release_tag:
    name: Release a tag
    permissions:
      contents: write
    uses: elastiflow/gha-reusable-workflows/.github/workflows/reusable_release_tag.yml@v0
